name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract PAGE_COLOUR from Dockerfile
        id: extract-color
        run: |
          PAGE_COLOUR=$(grep 'ENV PAGE_COLOUR=' Dockerfile | sed 's/ENV PAGE_COLOUR=//')
          echo "PAGE_COLOUR=${PAGE_COLOUR}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web-colour-app:${{ env.PAGE_COLOUR }}
          # tags: gachango/web-colour-app:${{ env.PAGE_COLOUR }}



      # - name: Update tag in test-alasco repo
      #   run: |
      #     git clone https://github.com/CharlesGM/test-alasco.git
      #     cd test-alasco
      #     sed -i "s/^image_tag = \".*\"/image_tag = \"${{ env.PAGE_COLOUR }}\"/" alasco/terraform.tfvars
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --global user.name "GitHub Actions"
      #     git add alasco/terraform.tfvars
      #     git commit -m "Update image_tag to ${{ env.PAGE_COLOUR }}"
      #     git push https://github.com/CharlesGM/test-alasco.git main


      - name: Logout from Docker Hub
        run: docker logout

